import '@mantine/core/styles.css';

import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from '@mantine/core';

import { theme } from '@/theme';

import type { Metadata } from "next";

import "./globals.css";

import Header from "@/components/page/Header";
import Footer from "@/components/page/Footer";
import styles from './layout.module.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <BodyContent>{children}</BodyContent>
        </MantineProvider>
      </body>

    </html>
  );
}

export const BodyContent = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <main className={styles.main}>
    <Header />
    <section className={styles.content}>
      {children}
    </section>
    <Footer />
  </main>
)
