export const ORDER_ADD_PRODUCT = "ORDER_ADD_PRODUCT";
export const ORDER_REMOVE_UNIT = "ORDER_REMOVE_UNIT";
export const ORDER_REMOVE_PRODUCT = "ORDER_REMOVE_PRODUCT";

export const SWITCH_LOCALE = "SWITCH_LOCALE";

export const CATEGORY_PARENT_UPDATE = "CATEGORY_PARENT_UPDATE";
export const CATEGORY_NAME_UPDATE = "CATEGORY_NAME_UPDATE";
export const CATEGORY_REMOVE = "CATEGORY_REMOVE";
