export const ORDER_ADD_PRODUCT = "ORDER_ADD_PRODUCT";
export const ORDER_REMOVE_UNIT = "ORDER_REMOVE_UNIT";
export const ORDER_REMOVE_PRODUCT = "ORDER_REMOVE_PRODUCT";

export const SWITCH_LOCALE = "SWITCH_LOCALE";

export const CATEGORY_PARENT_UPDATE = "CATEGORY_PARENT_UPDATE";
export const CATEGORY_NAME_UPDATE = "CATEGORY_NAME_UPDATE";
export const CATEGORY_REMOVE = "CATEGORY_REMOVE";
export const CATEGORY_CREATE = "CATEGORY_CREATE";

export const PRODUCT_UPDATE = "PRODUCT_UPDATE";
export const PRODUCT_REMOVE = "PRODUCT_REMOVE";

export const VAT_APPLY_VALUE_UPDATE = "VAT_APPLY_VALUE_UPDATE";
