export const ORDER_ADD_PRODUCT = "ORDER_ADD_PRODUCT";
export const ORDER_REMOVE_UNIT = "ORDER_REMOVE_UNIT";
export const ORDER_REMOVE_PRODUCT = "ORDER_REMOVE_PRODUCT";

export const SWITCH_LOCALE = "SWITCH_LOCALE";

export const CATEGORY_UPDATE = "CATEGORY_UPDATE";
